[package]
name = "raspi4_rust_bootloader"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "raspi4_rust_bootloader"
path = "src/main.rs"
test = false

[unstable]
build-std = ["core", "compiler_builtins"]

[profile.dev]
panic = "abort"
test-threads = 1

[profile.release]
panic = "abort"
